name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
        with:
          toolchain: stable
      - name: Check formatting
        run: cargo fmt --check
      - name: Test
        run: cargo test --locked --workspace
      - name: Clippy
        run: cargo clippy --locked --workspace --all-targets -- -D warnings
